Repository atos-df-rennes/prevarisc, pull requests merged in 2022-08, with the labels that each got.

#43 Filtrage des dossiers liés dans les avis & dérogations
  application/controllers/DossierController.php
  application/models/DbTable/Dossier.php
  application/views/scripts/dossier/avis-et-derogations-edit.phtml
  application/views/scripts/dossier/avis-et-derogations.phtml
  application/views/scripts/dossier/results/avisderogation/dossier.phtml
  application/views/scripts/dossier/results/avisderogation/liste-dossier.phtml
  public/css/main.css
  public/js/dossier/drop-list-button.js
Labels: enhancement

#46 #4783 - Correction de la relance de la périodicité
  application/services/Etablissement.php
Labels: bug

#42 Ordonnancement des rubriques et des champs
  application/controllers/FormulaireController.php
  application/forms/FormChampFromParent.php
  application/models/DbTable/Champ.php
  application/models/DbTable/Rubrique.php
  application/services/Formulaire.php
  application/views/scripts/formulaire/edit-champ.phtml
  application/views/scripts/formulaire/edit-rubrique.phtml
  application/views/scripts/formulaire/index.phtml
  application/views/scripts/formulaire/partials/partial-input-champ.phtml
  public/css/formulaire/formulaire.css
  public/css/formulaire/tableauInputParent.css
  public/js/formulaire/capsule-rubrique.js
  public/js/formulaire/ordonnancement/Sortable.js
  public/js/formulaire/ordonnancement/ordonnancement.js
  public/js/formulaire/rubrique.js
  sql/migrations/d-2.5-04-parentformulaire/2.5-01-ajout-type-champ-parent.sql
  sql/migrations/d-2.5-05-ordonnancement-formulaire/2.5-01-ajout-index-rubrique-champ.sql
Labels: enhancement

#38 Filtre de recherche pour les dossiers Plat'AU
  application/controllers/SearchController.php
  application/models/DbTable/Avis.php
  application/models/DbTable/Categorie.php
  application/models/DbTable/Commission.php
  application/models/DbTable/CommissionRegle.php
  application/models/DbTable/CommissionTypeEvenement.php
  application/models/DbTable/DateCommission.php
  application/models/DbTable/Dossier.php
  application/models/DbTable/DossierDocUrba.php
  application/models/DbTable/DossierListeDoc.php
  application/models/DbTable/Etablissement.php
  application/models/DbTable/EtablissementAdresse.php
  application/models/DbTable/Genre.php
  application/models/DbTable/ListeDocAjout.php
  application/models/DbTable/Search.php
  application/models/DbTable/Statistiques.php
  application/models/DbTable/Statut.php
  application/models/DbTable/TextesAppl.php
  application/models/DbTable/TypeTextesAppl.php
  application/services/Login.php
  application/services/Prescriptions.php
  application/services/Search.php
  application/views/scripts/search/dossier.phtml
Labels: enhancement, platau
