Repository atos-df-rennes/prevarisc, pull requests merged in 2023-05, with the labels that each got.

#77 [#4836] Impossible de créer une date dans le calendrier
  application/layouts/dossier.phtml
  application/views/scripts/dossier/index.phtml
Labels: bug, dossier

#78 Ajout de PHPStan
  .github/workflows/actions.yml
  application/controllers/CalendrierDesCommissionsController.php
  application/controllers/DossierController.php
  application/controllers/FormulaireController.php
  application/controllers/FusionDesCommunesController.php
  application/models/DbTable/DossierAffectation.php
  application/modules/api/services/Calendar.php
  composer.json
  composer.lock
  phpstan-baseline.neon
  phpstan.neon
Labels: enhancement

#79 Amélioration des messages d'erreur concernant la connexion avec Plat'AU
  application/services/Platau.php
Labels: invalid, platau

#59 [#4672] Recherche par préventionniste sur la recherche des établissements
  application/controllers/SearchController.php
  application/services/Search.php
  application/views/scripts/search/etablissement.phtml
Labels: enhancement, etablissement, recherche

#60 [#4671] Ajout de la liste des préventionnistes affectés dans la popup récapitulative d'un établissement
  public/js/main.js
Labels: enhancement, etablissement, recherche

#80 Correction d'erreurs PHPStan
  application/controllers/DossierController.php
  application/controllers/FormulaireController.php
  application/controllers/PieceJointeController.php
  application/models/DbTable/Etablissement.php
  phpstan-baseline.neon
Labels: bug

#81 Ajout des options de proxy dans les appels cURL
  application/services/Platau.php
  application/services/PlatauClient.php
Labels: bug, platau

#82 Le bouton de téléchargement des pièces jointes était affiché a un mauvais endroit
  application/controllers/PieceJointeController.php
  application/layouts/dossier.phtml
  application/navigation.xml
  application/views/scripts/calendrier-des-commissions/gestionodj.phtml
  application/views/scripts/piece-jointe/index.phtml
Labels: bug

#83 Ajout de Plugins optionnels
  application/layouts/etablissement.phtml
  application/plugins/FacteurCriticite.php
  application/plugins/LibelleDossierObservations.php
  application/plugins/LibelleDossierPrescriptions.php
  application/views/scripts/dossier/index.phtml
  application/views/scripts/dossier/prescription.phtml
  application/views/scripts/dossier/prescriptiontypeform.phtml
  application/views/scripts/gestion-des-commissions/index.phtml
  public/js/dossier/dossierGeneral.js
Labels: enhancement, etablissement, dossier

#84 Correction d'erreurs PHPStan
  application/Bootstrap.php
  application/controllers/AboutController.php
  application/controllers/AdminController.php
  application/controllers/CalendrierDesCommissionsController.php
  application/models/DbTable/Groupe.php
  application/services/Mail.php
  phpstan-baseline.neon
  phpstan.neon
Labels: bug, refactoring

#85 Correction de la surbrillance des onglets
  application/layouts/menu_admin.phtml
Labels: bug

#86 [#4817] Correction sur les erreurs de génération de documents de commission
  application/controllers/CalendrierDesCommissionsController.php
Labels: bug
