Repository atos-df-rennes/prevarisc, pull requests merged in 2023-09, with the labels that each got.

#61 [#4670] Affichage du nombre d'éléments d'un tableau de bord à l'ouverture de la page d'accueil
  application/controllers/IndexController.php
  application/models/DbTable/DateCommission.php
  application/models/DbTable/Dossier.php
  application/models/DbTable/Etablissement.php
  application/models/DbTable/Search.php
  application/services/Count.php
  application/services/Dashboard.php
  application/services/Feed.php
  application/views/scripts/index/index.phtml
  application/views/scripts/index/partials/commissions.phtml
  application/views/scripts/index/partials/commissions_bloc.phtml
  application/views/scripts/index/partials/dossiers.phtml
  application/views/scripts/index/partials/dossiers_bloc.phtml
  application/views/scripts/index/partials/dossiers_platau.phtml
  application/views/scripts/index/partials/dossiers_platau_bloc.phtml
  application/views/scripts/index/partials/etablissements.phtml
  application/views/scripts/index/partials/etablissements_bloc.phtml
  application/views/scripts/index/partials/feeds.phtml
  application/views/scripts/index/partials/feeds_bloc.phtml
  application/views/scripts/index/partials/odj.phtml
  application/views/scripts/index/partials/odj_bloc.phtml
Labels: enhancement, high priority

#115 Nettoyage de code non utilisé
  application/models/DbTable/Admin.php
  application/models/DbTable/DocManquantAdd.php
  application/models/DbTable/DossierEffectifDegagement.php
  application/models/DbTable/EffectifDegagement.php
  application/models/DbTable/EtablissementEffectifDegagement.php
  application/models/DbTable/GroupeGenre.php
  application/models/DbTable/GroupeNature.php
  application/models/DbTable/GroupeType.php
  application/models/DbTable/ListeDocManquant.php
  application/services/Effectifdegagement.php
  application/services/Interface/DataRepository.php
  application/services/Interface/GroupementCommunes.php
  sql/migrations/2.5-50-tables-effectifs-degagements.sql
  tools/composer.json
  tools/composer.lock
Labels: refactoring

#70 [#4815] Modification d'une adresse d'un établissement
  application/controllers/EtablissementController.php
  application/models/DbTable/AdresseCommune.php
  application/models/DbTable/AdresseRue.php
  application/models/DbTable/EtablissementAdresse.php
  application/modules/api/configs/routes.xml
  application/modules/api/services/Adresse.php
  application/modules/api/services/Etablissement.php
  application/services/Adresse.php
  application/views/scripts/etablissement/edit.phtml
  application/views/scripts/etablissement/partials/partial-adresse.phtml
  application/views/scripts/etablissement/partials/partial-modal-edit-adresse.phtml
  phpstan-baseline.neon
  public/js/etablissement/edit/geolocaliseIGN.js
  public/js/geoportail/manageMap.js
Labels: enhancement, etablissement

#117 Corrections d'affichage
  application/services/Utils.php
  application/views/scripts/dossier/results/avis-et-derogations.phtml
  public/css/etiquetteAvisDerogations/cardAvisDerogations.css
  public/css/formulaire/descriptif.css
Labels: bug, Style

#116 Ajout de tests unitaires
  .github/workflows/actions.yml
  .gitignore
  application/controllers/FormulaireController.php
  application/services/Dossier.php
  application/services/Etablissement.php
  application/services/Interface/TexteApplicable.php
  application/services/TextesApplicables.php
  application/services/Utils.php
  composer.json
  composer.lock
  tests/bootstrap/BootstrapTest.php
  tests/bootstrap/indexTest.php
  tests/plugins/SimpleFileDataStoreTest.php
  tests/services/AlertTest.php
  tests/services/DescriptifTest.php
  tests/services/PassAuthAdapterTest.php
  tests/services/TextesApplicablesTest.php
  tests/services/UtilsTest.php
Labels: enhancement

#118 Correction du téléchargement des pièces jointes
  application/controllers/PieceJointeController.php
  phpstan-baseline.neon
Labels: bug, platau, etablissement, dossier

#119 Correction de l'affichage des liens de téléchargement des pièces jointes
  application/controllers/EtablissementController.php
  application/controllers/PieceJointeController.php
Labels: bug, etablissement, dossier

#120 L'affichage du tableau de bord plantait si un bloc ne contenait pas de résultat
  application/models/DbTable/Search.php
  application/services/Feed.php
Labels: bug

#121 Corrige l'affichage des noms des champs de fusion
  application/controllers/FormulaireController.php
Labels: bug

#122 [#4870] Correction de l'erreur lors de l'ajout d'un établissement
  application/controllers/EtablissementController.php
  application/views/scripts/etablissement/edit.phtml
  phpstan-baseline.neon
  public/js/etablissement/edit/geolocaliseIGN.js
Labels: bug, etablissement
