Repository atos-df-rennes/prevarisc, pull requests merged in 2024-08, with the labels that each got.

#169 test(fonctionnel): mise en place de Cypress
  .gitignore
  cypress.config.js
  cypress/e2e/1.1-ajoutDossier.cy.js
  cypress/e2e/1.2-modifierDossier.cy.js
  cypress/e2e/1.3-rechercheDossiers.cy.js
  cypress/e2e/2.1-ajoutEtablissement.cy.js
  cypress/e2e/2.2-modifierEtablissement.cy.js
  cypress/e2e/2.3-rechercheEtablissements.cy.js
  cypress/e2e/authentification.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  sql/fixtures/suppression-dossiers-test.sql
  sql/fixtures/suppression-etablissements-test.sql
Labels: Tests

#170 fix: confirmation sur la suppression d'une dérogation
  application/controllers/DossierController.php
  application/views/scripts/dossier/results/avis-et-derogations.phtml
Labels: bug, dossier

#171 fix: génère les documents de commission même si le dossier n'a pas d'établissement
  application/controllers/CalendrierDesCommissionsController.php
Labels: bug, dossier

#172 feat: synchronisation des statuts des pièces jointes avec Plat'AU
  application/models/DbTable/PieceJointe.php
  application/views/scripts/dossier/prescription.phtml
  application/views/scripts/piece-jointe/display.phtml
  public/css/main.css
  sql/migrations/2.5-55-synchronisation-statut-platau.sql
Labels: enhancement, platau

#173 fix(fusion): évite de surcharger le champ de fusion
  application/services/Utils.php
  tests/services/UtilsTest.php
Labels: invalid
