Repository atos-df-rennes/prevarisc, pull requests merged in 2024-05, with the labels that each got.

#151 fix: Champs de fusion avis et dérogations uniquement pour ceux historisés
  application/controllers/CalendrierDesCommissionsController.php
  application/controllers/DossierController.php
  application/layouts/etablissement.phtml
  application/models/DbTable/Etablissement.php
  application/views/scripts/calendrier-des-commissions/generationcompterendu.phtml
  application/views/scripts/calendrier-des-commissions/generationconvoc.phtml
  application/views/scripts/calendrier-des-commissions/generationodj.phtml
  application/views/scripts/calendrier-des-commissions/generationpv.phtml
  application/views/scripts/dossier/creationdoc.phtml
Labels: invalid, dossier

#153 fix(carto): suppression de la couche carto par défaut sur l'ajout d'un établissement
  application/views/scripts/etablissement/edit.phtml
  public/js/etablissement/edit/geolocaliseIGN.js
  public/js/geoportail/manageMap.js
Labels: bug

#150 refactor: correction d'erreurs PHPStan
  .github/workflows/actions.yml
  application/controllers/CalendrierDesCommissionsController.php
  application/controllers/ChangementController.php
  application/controllers/CommissionController.php
  application/controllers/ContactController.php
  application/controllers/CouchesCartographiquesController.php
  application/controllers/DossierController.php
  application/controllers/ErrorController.php
  application/controllers/EtablissementController.php
  application/controllers/FusionDesCommunesController.php
  application/controllers/GestionDesCommissionsController.php
  application/controllers/GestionDesCommunesController.php
  application/controllers/GestionDesDocumentsController.php
  application/controllers/GestionPrescriptionsController.php
  application/controllers/GestionTextesApplicablesController.php
  application/controllers/GroupementController.php
  application/controllers/IndexController.php
  application/controllers/PieceJointeController.php
  application/controllers/SearchController.php
  application/controllers/SessionController.php
  application/controllers/StatistiquesController.php
  application/controllers/TableauDesPeriodicitesController.php
  application/controllers/UsersController.php
  composer.json
  phpstan-baseline.neon
  rector.php
  tools/composer.json
  tools/composer.lock
  tools/utils/rector/src/Rector/DynamicViewPropertyToAssignRector.php
Labels: refactoring

#154 fix: affectation de la date de commission d'un dossier en un seul clic
  application/views/scripts/dossier/index.phtml
Labels: bug

#156 fix(fusion): correction du non-remplacement de certaines balises
  application/controllers/CalendrierDesCommissionsController.php
  application/views/scripts/calendrier-des-commissions/generationcompterendu.phtml
  application/views/scripts/calendrier-des-commissions/generationconvoc.phtml
  application/views/scripts/calendrier-des-commissions/generationodj.phtml
  application/views/scripts/calendrier-des-commissions/generationpv.phtml
  application/views/scripts/dossier/creationdoc.phtml
Labels: bug, dossier
