Repository atos-df-rennes/prevarisc, pull requests merged in 2024-12, with the labels that each got.

#192 feat(dashboard): dossiers traités avec des PJs non envoyées
  application/services/Count.php
  application/services/Dashboard.php
  application/views/scripts/index/partials/dossiers_platau.phtml
  application/views/scripts/index/partials/dossiers_platau_bloc.phtml
  sql/migrations/2.5-58-dossiers-platau-pjs-erreur.sql
Labels: enhancement

#174 feat(formulaires): modification du nom des onglets
  application/controllers/DossierController.php
  application/controllers/EtablissementController.php
  application/controllers/FormulaireController.php
  application/layouts/dossier.phtml
  application/layouts/etablissement.phtml
  application/models/DbTable/CapsuleRubrique.php
  application/services/Formulaire.php
  application/views/scripts/formulaire/index.phtml
  application/views/scripts/formulaire/partials/partial-infos-rubriques.phtml
  application/views/scripts/formulaire/partials/partial-modal-editNom-capsuleRubrique.phtml
  phpstan-baseline.neon
Labels: enhancement, etablissement, dossier

#201 chore: MaJ des packages de dév
  tools/composer.lock
Labels: chore

#202 fix(pieces-jointes): permet de télécharger des gros fichiers
  application/controllers/DossierController.php
  application/views/scripts/piece-jointe/display.phtml
Labels: bug, dossier

#204 chore: mise à jour des paquets de développement
  tools/composer.json
  tools/composer.lock
Labels: chore
