Repository atos-df-rennes/prevarisc, pull requests merged in 2025-04, with the labels that each got.

#226 perf: optimisation des requêtes de recherche
  application/controllers/DossierController.php
  application/models/DbTable/Utilisateur.php
  application/modules/api/services/Calendar.php
  application/services/Etablissement.php
  application/services/Search.php
  application/services/User.php
  application/services/Valeur.php
  rector.php
  tests/plugins/SimpleFileDataStoreTest.php
  tests/services/DossierTest.php
  tests/services/NotificationTest.php
  tests/services/UtilsTest.php
  tools/composer.json
  tools/composer.lock
Labels: etablissement, dossier, recherche

#227 feat: recherche de dossier par identifiant PLAT'AU
  application/services/Search.php
Labels: enhancement, dossier

#230 fix: crash sur le bloc des erps sans prochaine vp pour un utilisateur n'ayant aucune commission
  application/services/Count.php
Labels: bug

#232 fix: timeout sur la génération du fichier d'export ODS des établissements et des dossiers
  application/controllers/SearchController.php
Labels: bug, high priority, recherche
